#############################################################################
# Makefile for building: huitasker
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Jan 21 19:22:06 2013
# Project:  ../huitasker2/huitasker/huitasker.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ -o Makefile ../huitasker2/huitasker/huitasker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I../huitasker2/huitasker -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include -I. -I. -I../huitasker2/huitasker -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../huitasker2/huitasker/main.cpp \
		../huitasker2/huitasker/showedmenu.cpp \
		../huitasker2/huitasker/pluginconnector.cpp \
		../huitasker2/huitasker/taskdialog.cpp \
		../huitasker2/huitasker/dialog.cpp moc_trayclass.cpp \
		moc_taskdbclass.cpp \
		moc_showedmenu.cpp \
		moc_pluginconnector.cpp \
		moc_taskdialog.cpp \
		moc_dialog.cpp
OBJECTS       = main.o \
		showedmenu.o \
		pluginconnector.o \
		taskdialog.o \
		dialog.o \
		moc_trayclass.o \
		moc_taskdbclass.o \
		moc_showedmenu.o \
		moc_pluginconnector.o \
		moc_taskdialog.o \
		moc_dialog.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		../huitasker2/huitasker/huitasker.pro
QMAKE_TARGET  = huitasker
DESTDIR       = 
TARGET        = huitasker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../huitasker2/huitasker/huitasker.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -o Makefile ../huitasker2/huitasker/huitasker.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -o Makefile ../huitasker2/huitasker/huitasker.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/huitasker1.0.0 || $(MKDIR) .tmp/huitasker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/huitasker1.0.0/ && $(COPY_FILE) --parents ../huitasker2/huitasker/trayclass.h ../huitasker2/huitasker/taskdbclass.h ../huitasker2/huitasker/showedmenu.h ../huitasker2/huitasker/echointerface.h ../huitasker2/huitasker/pluginconnector.h ../huitasker2/huitasker/taskdialog.h ../huitasker2/huitasker/dialog.h .tmp/huitasker1.0.0/ && $(COPY_FILE) --parents ../huitasker2/huitasker/main.cpp ../huitasker2/huitasker/showedmenu.cpp ../huitasker2/huitasker/pluginconnector.cpp ../huitasker2/huitasker/taskdialog.cpp ../huitasker2/huitasker/dialog.cpp .tmp/huitasker1.0.0/ && $(COPY_FILE) --parents ../huitasker2/huitasker/widget.ui ../huitasker2/huitasker/dialog.ui .tmp/huitasker1.0.0/ && (cd `dirname .tmp/huitasker1.0.0` && $(TAR) huitasker1.0.0.tar huitasker1.0.0 && $(COMPRESS) huitasker1.0.0.tar) && $(MOVE) `dirname .tmp/huitasker1.0.0`/huitasker1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/huitasker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_trayclass.cpp moc_taskdbclass.cpp moc_showedmenu.cpp moc_pluginconnector.cpp moc_taskdialog.cpp moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_trayclass.cpp moc_taskdbclass.cpp moc_showedmenu.cpp moc_pluginconnector.cpp moc_taskdialog.cpp moc_dialog.cpp
moc_trayclass.cpp: ../huitasker2/huitasker/showedmenu.h \
		../huitasker2/huitasker/taskdbclass.h \
		../huitasker2/huitasker/dialog.h \
		../huitasker2/huitasker/trayclass.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ../huitasker2/huitasker/trayclass.h -o moc_trayclass.cpp

moc_taskdbclass.cpp: ../huitasker2/huitasker/showedmenu.h \
		../huitasker2/huitasker/taskdbclass.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ../huitasker2/huitasker/taskdbclass.h -o moc_taskdbclass.cpp

moc_showedmenu.cpp: ../huitasker2/huitasker/showedmenu.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ../huitasker2/huitasker/showedmenu.h -o moc_showedmenu.cpp

moc_pluginconnector.cpp: ../huitasker2/huitasker/echointerface.h \
		../huitasker2/huitasker/dialog.h \
		../huitasker2/huitasker/taskdbclass.h \
		../huitasker2/huitasker/showedmenu.h \
		../huitasker2/huitasker/trayclass.h \
		../huitasker2/huitasker/pluginconnector.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ../huitasker2/huitasker/pluginconnector.h -o moc_pluginconnector.cpp

moc_taskdialog.cpp: ../huitasker2/huitasker/taskdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ../huitasker2/huitasker/taskdialog.h -o moc_taskdialog.cpp

moc_dialog.cpp: ../huitasker2/huitasker/dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ../huitasker2/huitasker/dialog.h -o moc_dialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h ui_dialog.h
ui_widget.h: ../huitasker2/huitasker/widget.ui
	/usr/bin/uic ../huitasker2/huitasker/widget.ui -o ui_widget.h

ui_dialog.h: ../huitasker2/huitasker/dialog.ui
	/usr/bin/uic ../huitasker2/huitasker/dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../huitasker2/huitasker/main.cpp ../huitasker2/huitasker/trayclass.cpp \
		../huitasker2/huitasker/trayclass.h \
		../huitasker2/huitasker/showedmenu.h \
		../huitasker2/huitasker/taskdbclass.h \
		../huitasker2/huitasker/dialog.h \
		../huitasker2/huitasker/echointerface.h \
		../huitasker2/huitasker/taskdialog.h \
		../huitasker2/huitasker/taskdbclass.cpp \
		../huitasker2/huitasker/pluginsl.h \
		../huitasker2/huitasker/pluginconnector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../huitasker2/huitasker/main.cpp

showedmenu.o: ../huitasker2/huitasker/showedmenu.cpp ../huitasker2/huitasker/showedmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o showedmenu.o ../huitasker2/huitasker/showedmenu.cpp

pluginconnector.o: ../huitasker2/huitasker/pluginconnector.cpp ../huitasker2/huitasker/pluginconnector.h \
		../huitasker2/huitasker/echointerface.h \
		../huitasker2/huitasker/dialog.h \
		../huitasker2/huitasker/taskdbclass.h \
		../huitasker2/huitasker/showedmenu.h \
		../huitasker2/huitasker/trayclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pluginconnector.o ../huitasker2/huitasker/pluginconnector.cpp

taskdialog.o: ../huitasker2/huitasker/taskdialog.cpp ../huitasker2/huitasker/taskdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskdialog.o ../huitasker2/huitasker/taskdialog.cpp

dialog.o: ../huitasker2/huitasker/dialog.cpp ../huitasker2/huitasker/dialog.h \
		../huitasker2/huitasker/ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o ../huitasker2/huitasker/dialog.cpp

moc_trayclass.o: moc_trayclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trayclass.o moc_trayclass.cpp

moc_taskdbclass.o: moc_taskdbclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskdbclass.o moc_taskdbclass.cpp

moc_showedmenu.o: moc_showedmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_showedmenu.o moc_showedmenu.cpp

moc_pluginconnector.o: moc_pluginconnector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pluginconnector.o moc_pluginconnector.cpp

moc_taskdialog.o: moc_taskdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskdialog.o moc_taskdialog.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

